# Generated by Django 3.0.5 on 2020-04-08 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Decan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Деканат')),
                ('description', models.CharField(max_length=300, verbose_name='Комментарий')),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'verbose_name': 'Деканат',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Преподаватель')),
                ('description', models.TextField(verbose_name='Информация о пользователе')),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'verbose_name': 'Преподаватель',
            },
        ),
    ]
